# Generated by Django 4.2.3 on 2023-07-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='address',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='employment_type',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
