# Generated by Django 3.2.20 on 2023-08-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230811_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='bank_statement',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='payslip',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
